### PR TITLE
Fix user data duplication on user login

### LINKED ISSUE #202: User roles are duplicated when logging in/out
## Problem

When a user logs out and in again, their user roles are duplicated.

### Steps to reproduce

1. Clone this repository.
2. Provide the necessary authentication files: `oauth2.edn` and `admin.edn` (see [Configuration files](https://github.com/skydread1/flybot.sg#config-files)).
3. Initialize the website for web development (see [Front-end dev setup](https://github.com/skydread1/flybot.sg#dev)).
4. Log in to the website and check `@re-frame.db/app-db` in the ClojureScript REPL.
    The user (in `:app/user`) should contain roles like these (note the duplicate entries):
    ```clojure
    [#:role{:name :editor,
            :date-granted #inst "2023-07-24T09:41:00.000-00:00"}
     #:role{:name :admin,
            :date-granted #inst "2023-07-24T09:41:00.000-00:00"}
     #:role{:name :editor,
            :date-granted #inst "2023-07-24T09:41:00.000-00:00"}
     #:role{:name :admin,
            :date-granted #inst "2023-07-24T09:41:00.000-00:00"}]
    ```
5. Log out and log in again *n* times, then check `@re-frame.db/app-db` in the ClojureScript REPL.
    The user should contain the same roles as above, duplicated exactly 2<sup>*n*</sup> more times.

## Suggestion

Remove user roles before updating user information during login.

### PR DESCRIPTION
**Pull request by flybot-nam-nguyenhoai**
## Closes #202

- [x] Remove unused user information (e.g., user roles) when updating user information during login.

### CODE REVIEW

File: server/src/flybot/server/core/handler/operation.clj [hunk 1]
```diff
@@ -75,7 +75,13 @@
...
+    (let [updated-user (-> user
+                           (select-keys [:user/id
+                                         :user/email
+                                         :user/name
+                                         :user/picture])
+                           (merge #:user{:name name
+                                         :picture picture}))]
     ;; already in db so update user (name or picture could have changed).
       {:response updated-user
        :effects  {:db {:payload [updated-user]}}
```
Comment (skydread1) [inline server/src/flybot/server/core/handler/operation.clj:87]:
```clojure
{:response (merge user updated-user) ;; roles expected in the response
  :effects  {:db {:payload [updated-user]}}
```

File: server/src/flybot/server/core/init_data.clj [hunk 2]
```diff
@@ -79,8 +79,8 @@
           :css-class "welcome"
           :creation-date (u/mk-date)
           :last-edit-date (u/mk-date)
-          :author user-admin
-          :last-editor user-admin
+          :author (select-keys user-admin [:user/id])
```
Comment (skydread1) [inline server/src/flybot/server/core/init_data.clj:82]:
```clojure
:author (:user/id user-admin)
```

**Review by skydread1 — CHANGES_REQUESTED** [review]

File: server/src/flybot/server/core/handler/operation.clj (hunk 1 above)
Comment (flybot-nam-nguyenhoai) [reply server/src/flybot/server/core/handler/operation.clj]: Fixed.

**Review by skydread1 — APPROVED** [review]
