### PR TITLE
247 post title mobile fix

### LINKED ISSUE #247: `post->title` does not work on mobile app
## Problem

`post->title` is in the namespace `flybot.client.web.core.utils` which is a namespace dedicated to web utils only.

However, this function was called in several `common` namespaces such as in `flybot.client.common.db.event`. It was also called directly called in mobile namespace such as `flybot.client.mobile.core.db.event`.

`post->title` relies on [markdown-to-hiccup](https://github.com/mpcarolin/markdown-to-hiccup) which has deps on [clj-commons/hickory](https://github.com/clj-commons/hickory).

Hickory uses some web dom logic in their conversion logic which does not work with nodejs. It was discussed in issue [#17](https://github.com/clj-commons/hickory/issues/17) and a PR merged for it [#33](https://github.com/clj-commons/hickory/commit/ab2e384c02405082db1c4ee8c6d53c1f0d38acad).

Some npm tiers packages are required to be added in the react native deps in order to make it work in nodejs. The packages suggested in the PR33 are:
- `jsdom`: which does not work with figwheel
- `xmldom`: which has critical vulnerabilities

## Suggestion

The mobile development not being a priority right now, we can use a `goog-define` to only require `markdown-to-hiccup` at runtime in the web build.

- `post->title` can only use markdown parsing for the mobile app
- `has-valid-h1-title?` can have a markdown parsing logic to cover most cases in the meantime in the mobile app

Also `post->title` needs to be moved in a common namespace such as `flybot.client.common.utils`

### PR DESCRIPTION
**Pull request by skydread1**
Closes #247
---

- move `post->title` to `flybot.client.common.utils`
- use goog-define `MOBILE?` flag to only require `markdown-to-hiccup` on the web client

### CODE REVIEW

File: client/common/src/flybot/client/common/utils.cljs [hunk 1]
```diff
@@ -1,8 +1,15 @@
 (ns flybot.client.common.utils
   "Rendering app notifications as pop-up `toast` notifications in the DOM."
```
Comment (flybot-nam-nguyenhoai) [inline client/common/src/flybot/client/common/utils.cljs:2]: Incorrect namespace docstring.

**Review by flybot-nam-nguyenhoai — APPROVED** [review]
Looking good, tests passed without any warnings. Ready to merge.
